### PR TITLE
Update Spanish.properties

### PR DESCRIPTION
**Pull request by Hello200000**
Translation of almost the entire constructions folder

### CODE REVIEW

**Comment by Hello200000** [comment]
What does wildcard mean?

**Comment by Hello200000** [comment]
There are several bugs in the mod
1. Units cannot be healed with the instant heal promotion.
2. When the city bombards a unit it does not deal damage.

These are the bugs I have found so far.

**Comment by DW8030** [comment]
A wildcard is a card that you can use for different things, like a Joker. 

I did fix the heal bug quite a while ago I believe. It's apparently broken again, I'll see if I can fix that.

You should build walls in your city, you shouldn't be able to bombard units with the city before you have them. That's why I set it to -100% strength when attacking. Does it work if you build walls?

**Comment by DW8030** [comment]
I found it I think. I replaced some archaic terminology in the healing promotion by the new unique, it should work now. Thank you.

**Pull request merged**
